apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: customer-orders-api
    newName: acrazlegacydev001.azurecr.io/customer-orders-api
    newTag: dev

patches:
  - target:
      kind: Deployment
      name: customer-orders-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
