apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-orders-config
  namespace: customer-orders
data:
  APP_NAME: "Customer Orders API"
  APP_ENV: "kubernetes-local"
  APP_VERSION: "0.4.0"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "customer_orders"
  POSTGRES_DB: "customer_orders"
