apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: customer-orders
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: azure-legacy-app-migration-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
