apiVersion: v1
kind: Service
metadata:
  name: customer-orders-api
  namespace: customer-orders
  labels:
    app.kubernetes.io/name: customer-orders-api
    app.kubernetes.io/part-of: azure-legacy-app-migration-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: customer-orders-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: customer-orders-api
  namespace: customer-orders
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: customer-orders-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - customer-orders
